service: ms-oic-smartfit

provider:
  name: aws
  runtime: nodejs10.x
  stage: v1
  region: us-east-1
  timeout: 30
  memorySize: 512
  versionFunctions: false
  vpc:
    securityGroupIds:
      - sg-34311250
      - sg-265dc142
    subnetIds:
      - subnet-9ef492e9
      - subnet-65eb444e
  environment:
    APPLICATION_NAME: ms-oic-smartfit
  package:
    excludeDevDependencies: true
    exclude:
      - .git/**
      - .vscode/**

functions:
  app: 
    name: ms-oic-smartfit
    handler: handler.run
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-offline
